### ISSUE TITLE
[Bug] TotK-RstbCalculator does not reset the cached vanilla RSTB file when changing the dump version

### ISSUE THREAD

**Issue by MasterBubbles** [TKMM-Team/Tkmm#22]

**Comment by MasterBubbles** [comment]
When changing the game path setting to a different dump version and clicking save, TotK-RstbCalculator will keep the vanilla RSTB file from the previous dump in cache, and merging will continue to generate a resource table for the previous version (until closing and reopening TKMM)

**Comment by ArchLeaders** [comment]
The vanilla file is parsed every time a new RstbGenerator is constructed. Can you provide steps to create and verify that this is occurring?

**Comment by MasterBubbles** [comment]
Open TKMM, merge a first time, go to the settings, change the dump location to a different version of the game, then merge a second time. The second time it merges, it will still use the previous version for the resource table. RSDB files on the other hand are correct

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/TKMM-Team/Tkmm/commit/f68c4c166de134badebf134f098eddc2d30985a9
