### ISSUE TITLE
Pchtxt files ignored in the final merged output folder when 2 mods uses the exefs folder

### ISSUE THREAD

**Issue by MelonSpeedruns** [TKMM-Team/Tkmm#31]
If a mod like UltraCam (https://gamebanana.com/mods/480138) has an `exefs` folder with `main.npdm` and `subsdk3` inside, and another mod like Kingdom Rebalance (https://gamebanana.com/mods/478892) has a few .pchtxt files inside, the final `Merged Output` folder won't include the .pchtxt files. They have to be copied-in manually after the fact.

This is on Windows btw, in case it matters.

**Comment by MasterBubbles** [comment]
Normally .pchtxt files are meant to be merged and converted to .ips files by TKMM, did you verify that there were .ips files?

**Comment by ArchLeaders** [comment]
`.pchtxt` files are not copied into the mod output, they are converted to `.ips`.
