### ISSUE TITLE
Unwanted Bootup pack in romfs/Pack/Actor

### ISSUE THREAD

**Issue by Echocolat** [TKMM-Team/Tkmm#34]
Upon merging one or multiple mods that contains a romfs/Pack/Bootup file, TKMM adds a copy of it in romfs/Pack/Actor.
Tested on TKMM v1.0.0-beta9.

**Comment by ArchLeaders** [comment]
@okmika can you look into this, or would you prefer if I look into it?

**Comment by ArchLeaders** [comment]
@Echocolat are you sure this isn't just an issue with Challenge Mode?

![image](https://github.com/user-attachments/assets/fe57210e-9183-454c-91c1-9005394555d5)

**Comment by Echocolat** [comment]
Generated the 1.1.0 to 1.2.1 versions with TKMM

**Comment by ArchLeaders** [comment]
Ah okay, probably an issue with the packager then.

It's not the merger, at any rate, other mods with Bootup.pack don't have this issue.

**Comment by Echocolat** [comment]
I'll take a look later. Also, the mod files rn are borked because I forgot to rename AI Global and recalculate RESTBL after reading Mals lmao (fix soon)

**Comment by ArchLeaders** [comment]
Packaging works fine on my end. Let me know if you can recreate it, but it seems to be a user error.

(There's no reason for this error to occur. Everything is dealt with the same, so if one file gets misplaced they all would be)

**Comment by Echocolat** [comment]
Seems like I didn't get that issue with the dev versions I built myself from source. I consider this solve, thank you for looking at it and sorry to have wasted your time!
