### ISSUE TITLE
RSDB Merging Issue

### ISSUE THREAD

**Issue by dt-12345** [TKMM-Team/Tkmm#35]
(copied exactly from the discord bug report bc I figured I should probably actually open a github issue lol, only thing is github doesn't support byml files so I can't upload the actual file in the issue)

I'd open an issue on GitHub, but skimming through both RsdbMerger and BymlLibrary, I couldn't quite tell where the issue could be coming from. It seems that when merging PouchActorInfo files for certain mods, the merger will output a file with node type 0xFE for certain IsUsable nodes (supposed to be 0xD0 for bool). This can occur when merging a mod with itself (such as merging Cook Or Die with itself) or when merging different mods together. This issue is present in both the changelog and the output file (sample file attached). While this does not cause the game to crash, it can lead to unintended behavior as the game will default to false for these invalid nodes even if they are intended to be set to true. It also makes editing the merged files impossible as tools will fail to parse the files. I've also attached an image with the locations of the invalid nodes in the sample file for reference. As far as I can tell, this only occurs for IsUsable nodes for some reason.
![image](https://github.com/user-attachments/assets/d0158574-7b57-4bbe-bada-256b091b172f)

**Comment by ArchLeaders** [comment]
This is expected behaviour for the changelog files, but it should not be present in the merged output.

Can you send the files (zipped) or links to two mods that will cause this?

**Comment by ArchLeaders** [comment]
Also to clarify, the invalid node type is something used by TKMM to store extra merging/changelog information outside of Nintendo's BYML spec.

To open the special format, you can use [Totk Register Toolkit](https://github.com/ArchLeaders/TotkRegistryToolkit), however it only works on Windows.

**Comment by dt-12345** [comment]
[files.zip](https://github.com/user-attachments/files/16684109/files.zip)

These are from echo, I believe the before is challenge mode's cook or die option before TKMM and the after is after TKMM

**Comment by ArchLeaders** [comment]
The merged output has no errors on my end. Can you confirm you (or Echo) are using the latest version (1.0.0-beta9)?

**Comment by ArchLeaders** [comment]
I figured it out now, just needed to test it properly.
