### ISSUE TITLE
Launcher crashes when starting

### ISSUE THREAD

**Issue by AmerusTheMan** [TKMM-Team/Tkmm#36]
As soon as i start the launches, it loads a bit but then stops. I dont get a screen and there is nothing that runs in the background. I have installed net runtime(x64).

**Comment by ArchLeaders** [comment]
Can you type `dotnet --list-runtimes` in CMD (Command Prompt) and send a screenshot of the results?

**Comment by AmerusTheMan** [comment]
Sorry for the long response time, here is the screenshot
![image_2024-08-21_184316051](https://github.com/user-attachments/assets/31eccf29-638e-4c71-b31c-98b684231a9d)

**Comment by ArchLeaders** [comment]
Is it possible that you have an antivirus blocking the launcher?

**Comment by AmerusTheMan** [comment]
no, at least i dont think so(it's a family computer)

**Comment by ArchLeaders** [comment]
The TKMM assemblies aren't signed, so it's quite possible.

If you have any antivirus software (Windows Defender at the least), try excluding the exe and see if that helps.

Also, make sure the app isn't blocked from connecting to the internet, that may be causing it to crash.

**Comment by AmerusTheMan** [comment]
I've added the launcher as an exeption to the windows defender and it still dosn't work, how do i see if the app is blocked from the internet

**Comment by ArchLeaders** [comment]
If the app couldn't access the internet it would be blocked by a firewall rule. You can check in the advanced Windows firewall settings, but I highly doubt that's the issue.

I don't really have any other ideas though, apart from another antivirus or possibly a broken config.

You can fix the latter problem by deleting the folders `%localappdata%\totk`, `%localappdata%\tkmm` and `%appdata%\tkmm` (if they exist). I don't know why those would be corrupt, but it's worth a shot.

**Comment by AmerusTheMan** [comment]
I messed around a bit and somehow got it to work, here is everything i did diferently:
I unziped with 7z
i redownloaded to c:\ and ran it from there. Previusly i had downloaded it to another drive but tried on both.
I uninstalled and reinstalled net runtime(i had already tried this before)

**Comment by ArchLeaders** [comment]
Hmm, I wonder if became corrupted when it was unzipped somehow. Or maybe the drive you had it from couldn't be run on.

Anyway, glad you figured it out.
