### ISSUE TITLE
[Bug] Expect dynamic address and value lengths in pchtxt files

### ISSUE THREAD

**Issue by xCatchyx** [TKMM-Team/Tkmm#40]
I have tried these two mods in a couple ways, No World Limits 1.2.1, and Disable Healing In Combat, both of these mods contents are exclusively patch.txt files as far as I am aware, and when trying to merge any mods, at all, with these mods enabled, throw an ArgumentOutOfRange error every time.

I even tried merging only these two mods, exact same error, once disabling them, no issues with merging at all.

![image](https://github.com/user-attachments/assets/1ffc46a7-530c-4e1c-82aa-228957911f4d)

**Comment by ArchLeaders** [comment]
There is probably something unexpected in the files, I'll take a look.
