### ISSUE TITLE
Option Mals Priority

### ISSUE THREAD

**Issue by dt-12345** [TKMM-Team/Tkmm#42]
((forwarded from echo))
When merging an option that contains a Mals file, the base mod's Mals file will be merged with a higher priority than the option leading to any changes in the option's Mals being ignored.

**Comment by ArchLeaders** [comment]
Do you think you could send me a sample file that I can use to replicate and test this?

**Comment by dt-12345** [comment]
Installing Challenge Mode with the Brazilian Portuguese option, Echo says that you can check Item_Enemy_900 in the PouchContent msbt as an example.

**Comment by ArchLeaders** [comment]
Can you send the file? I don't have a TKCL of Challenge Mode, and I'm not in the Discord server.

**Comment by dt-12345** [comment]
It's too large for GitHub but Greem sent it in #beta-testing on the server

**Comment by ArchLeaders** [comment]
Cool, thanks. I found the issue without it anyway, sorry for the bother.
