### ISSUE TITLE
(Suggestion) Allow signing into Gamebanana to get mods marked as questionable/nsfw

### ISSUE THREAD

**Issue by RowanSkie** [TKMM-Team/Tkmm#44]
I really like the Gamebanana browser of the app, however it doesn't allow one to log in which can allow people to show other mods marked as NSFW or similar markings that cause it to disappear during guest view.

**Comment by ArchLeaders** [comment]
I don't stand for anything NSFW, so you'll have to fork and implement this yourself. Anything to do with this subject will not be associated with TKMM while I am part of the project.

If you want to do this, you can use the website. (For extra convenience you can drag the URL over TKMM to install the mod like you would from the GB browser.)
