### ISSUE TITLE
[Bug] Custom BYML arrays are not merged

### ISSUE THREAD

**Issue by AsteroidPizza39** [TKMM-Team/Tkmm#47]
(forwarding on behalf of Miirkuz)

so basically i've built my mod DAR and wanted to make a compatibility patch to make DAR compatible with Challenge Mode.
one of the things that the patch contain is the chance to make Golden Enemies (from Challeng Mode) drops custom DAR items like chest keys and other stuff.
what i have noticed is that if i put my patch with higher priority than Challenge Mode, everything is merged correctly except my edits on golden enemies droptables, while if i put my patch with lower priority than Challenge Mode, droptables are merged fine but other edits on golden enemies actors are not merged. 
Same thing with Mals, since both DAR and Challenge Mode change the text of 'Game Over' with 'You Died' (DAR) and with 'Defeat' (Challenge Mode), when DAR has higher priority than Challenge Mode, i would expect that when i die i see the 'You Died' text from DAR, but i got 'Defeat' from Challenge Mode.
I've put my DAR mals inside the compatibility patch, and put it with lower priority than Challenge Mode, and this fixed my problem, but i don't think that's how it supposed to be.
so to me, looks like that tkmm confuses the priority order on droptables and Mals.
Let me know what you think or if you need extra info or the mods files.
Thank you in advance and this is my e-mail: miirkuz@gmail.com

**Comment by ArchLeaders** [comment]
The issue with mals was fixed in #42 (the entire mod list was reversed by MalsMerger), the latest master should work.

As for the drop table issue; I don't know how to doctor a test for this, so do you think you could send the patch you used or a sample mod that replicates the issue?

Feel free to [email me](mailto:archleaders@outlook.com) if you would prefer your files not be posted publicly here.

**Comment by ArchLeaders** [comment]
Same issue as https://github.com/okmika/TKMM-SARC/issues/12

**Comment by ArchLeaders** [comment]
Waiting for https://github.com/okmika/TKMM-SARC/issues/13
