### ISSUE TITLE
[Test] Versioned files must always use the AddressTable file name

### ISSUE THREAD

**Issue by Echocolat** [TKMM-Team/Tkmm#59]
The versioned file `romfs/Logic/NodeDefinition/Node.Product.{ver}.aidefn.byml.zs` does not merge properly when the .tkcl file was packaged on a version that is different than the version it's installed on. For example, packaging an edited Node.Product file on 1.1.0 will make it so that the .tkcl changelog keeps the "110" name
![image](https://github.com/user-attachments/assets/2feee2c7-326d-4fad-a142-8c093360d0ae)
When installing this .tkcl on 1.2.1, the Node.Product file will be correctly named, but will *only* contain the changelog as its content, which is obviously going to fataly crash the game upon booting a save file.
![image](https://github.com/user-attachments/assets/6deda732-f116-44c5-b5a7-aa5d5c8ce892)
Here's a screenshot of the raw edited file, that is about 16kb in size.
![image](https://github.com/user-attachments/assets/404267fd-2b0d-48ab-9eae-e66cc4658e4b)

**Comment by ArchLeaders** [comment]
This is a known issue, it will be fixed in the next version. Thanks.
