### ISSUE TITLE
Feature Request: Developer/Advanced Options

### ISSUE THREAD

**Issue by charlie92155** [TKMM-Team/Tkmm#66]
I know you may be hesitant to add some of these features because they could create snowball of issues, but maybe under a developer /advanced setup. 

Option to explore the folder of the installed mod

Requesting Developer/Super User Install Options when Installing Mods:

Option to make patch mod (anything installed as a patch would overwrite lower priority files instead of merging them) 

OR

Options where you can disable shop merger
Options to disable map merging
Options to disable maybe other Sarc/Actor Mergers (specifically for issues with drop table list merging)

**Comment by ArchLeaders** [comment]
This already exists. You need to build from the source in debug mode. This will always be the only way to access debug/development features like this.

Unfortunately, it's not worth the time it takes to troubleshoot the less advanced users using this system to make these features even accidentally accessible.

Sorry for the inconvenience, but this is the best we can do.

(Note: to disable a merger, remove it (comment it out) from the mergers list and rebuild)
