### ISSUE TITLE
[Bug] Options are not merged correctly

### ISSUE THREAD

**Issue by AsteroidPizza39** [TKMM-Team/Tkmm#7]
When a mod has options selected (tested with all 4 types of option groups), the options will not be merged into the romfs folder in the merged output folder, but stay in a separate `options` folder within the target merge folder. Attached is a .ZIP containing a TKCL to test this with.
![image](https://github.com/TKMM-Team/Tkmm/assets/45804670/63da61c5-1c14-4ce0-af0b-d83c9c8da176)
[ArmorIconToolOptions001.zip](https://github.com/user-attachments/files/15604075/ArmorIconToolOptions001.zip)

**Comment by ArchLeaders** [comment]
This is an issue with sarc tool.: https://github.com/okmika/TKMM-SARC/issues/5
