### ISSUE TITLE
[Bug] Vanilla Layouts/Layout Animations included in changelog

### ISSUE THREAD

**Issue by AsteroidPizza39** [TKMM-Team/Tkmm#8]
Within `UI\LayoutArchive\Common.Product.110.Nin_NX_NVN.blarc.zs`, the majority of the `.bflyt` and `.bflan` are stored. These are the layouts and layout animations. Even if a given one of these files is unmodified, it is read as a modified file. Since there's no library for merging layouts and their animations, they are priority based, so if two mods edit layouts, only the mod with the higher priority will have the modified layout applied, since its vanilla layout files have higher priority than the lower mod's modded layout file. Attached is a zip containing a mod that edits a layout file, specifically `Pouch_00.bflyt`.
[ArmorIconToolOptions001.zip](https://github.com/user-attachments/files/15604115/ArmorIconToolOptions001.zip)

**Comment by ArchLeaders** [comment]
According to TotkBits every file in that archive is modified. Probably an issue on the tooling side.

**Comment by ArchLeaders** [comment]
Actually never mind, this appears to be an issue with TotkBits. However, it's likely that both bugs are related to the hash algorithm being messed up somewhere.

**Comment by okmika** [comment]
Fixed in https://github.com/okmika/TKMM-SARC/pull/7
