### ISSUE TITLE
[Bug] HeadDef is not compressed correctly

### ISSUE THREAD

**Issue by ArchLeaders** [TKMM-Team/Tkmm#9]
> The HeadDef (`System/HeapSize/Product.Nin_NX_NVN.HeapDef.byml.zs`) file is currently being re-compressed with dictionary `1` (`zs.dic`).
> 
> However, this file is loaded before dictionaries, so it must not use any dictionaries in the compression.

https://github.com/okmika/TKMM-SARC/issues/6

**Comment by okmika** [comment]
Fixed in https://github.com/okmika/TKMM-SARC/pull/7
